version: '3.4'

services:

  moduledb:
    container_name: "moduledb"
    restart: always
    volumes: ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  module.api:
    container_name: "moduleapi"
    ports:
      - 8000:80
      - 8001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Computer1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ModuleDatabaseSettings:ConnectionString=mongodb://moduledb:27017"
    depends_on: 
      moduledb
    volumes:
      - ~/.aspnet/https:/https:ro
